Repository redhat-beyond/HighTeach, pull requests merged in 2023-04, with the labels that each got.

#22 Add ERD.pdf file
  ERD.pdf
Labels: Status/New, documentation

#23 Adding DFD file
  DFD.pdf
Labels: Status/In-Progress, documentation

#26 move ERD and DFD diagrams to documents folder
  documents/diagrams/DFD.pdf
  documents/diagrams/ERD.pdf
Labels: documentation

#25 Update the setup.sh
  setup.sh
Labels: Status/New, Ready for maintainer review

#48 Adding Users app
  HighTeach/settings.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_profile_bio_profile_profession.py
  users/migrations/__init__.py
  users/models.py
  users/signals.py
  users/tests.py
  users/views.py
Labels: Status/New, enhancement, Ready for maintainer review

#39 Create the Course app
  HighTeach/settings.py
  course/__init__.py
  course/admin.py
  course/apps.py
  course/migrations/0001_initial.py
  course/migrations/__init__.py
  course/models.py
  course/tests.py
  course/views.py
Labels: enhancement, Ready for maintainer review

#49 Adding pytest-django to the project.
  Pipfile
  Pipfile.lock
  pytest.ini
Labels: Status/New, enhancement, Ready for maintainer review

#31 Create the Teacher Course
  HighTeach/settings.py
  course/admin.py
  course/migrations/0001_initial.py
  course/models.py
Labels: Status/In-Progress, enhancement, Ready for maintainer review

#37 Update ERD
  documents/diagrams/ERD.jpeg
  documents/diagrams/ERD.pdf
Labels: Status/New, documentation, Ready for maintainer review

#35 Create a chat app
  HighTeach/settings.py
  chat/__init__.py
  chat/admin.py
  chat/apps.py
  chat/migrations/0001_initial.py
  chat/migrations/__init__.py
  chat/models.py
  chat/tests.py
  chat/views.py
Labels: Status/In-Progress, enhancement, Ready for maintainer review

#50 Create the study_group app
  HighTeach/settings.py
  study_group/__init__.py
  study_group/admin.py
  study_group/apps.py
  study_group/migrations/0001_initial.py
  study_group/migrations/0002_test_data.py
  study_group/migrations/__init__.py
  study_group/models.py
  study_group/tests.py
  study_group/views.py
  tests/conftest.py
  tests/study_group/test_group_manager.py
  tests/study_group/test_study_group.py
Labels: enhancement, Ready for maintainer review

#56 Create the Review tests and update the models.py
  course/migrations/0002_alter_review_student_id_and_more.py
  course/models.py
  course/tests.py
  tests/course/test_for_review_course.py
Labels: enhancement, Ready for maintainer review

#63 Update ERD
  documents/diagrams/ERD.jpeg
  documents/diagrams/ERD.pdf
Labels: Status/New, documentation, Ready for maintainer review

#47 Adding Student Course
  course/admin.py
  course/migrations/0003_studentcourses_and_more.py
  course/models.py
  tests/course/test_for_courses.py
Labels: enhancement, Ready for maintainer review

#59 Create test file for teacher course model
  course/models.py
  tests/course/test_for_course.py
  tests/course/test_for_review_course.py
Labels: Status/New, Ready for maintainer review
