Repository redhat-beyond/HighTeach, pull requests merged in 2023-03, with the labels that each got.

#1 Useful information in README
  HighTeach_logo.jpeg
  README.md
Labels: Status/In-Progress, documentation

#9 Adding a Django development environment to the VM
  HighTeach/__init__.py
  HighTeach/asgi.py
  HighTeach/settings.py
  HighTeach/urls.py
  HighTeach/wsgi.py
  Pipfile
  Pipfile.lock
  manage.py
Labels: Status/In-Progress, enhancement

#12 Adding setup.sh file and update Vagrantfile
  Vagrantfile
  setup.sh
Labels: Status/New, enhancement

#17 Useful information added to README.md file
  README.md
Labels: Status/In-Progress, documentation
