Repository redhat-beyond/HighTeach, pull requests merged in 2023-05, with the labels that each got.

#60 Add chat tests and update validation of message creation.
  chat/migrations/0002_message_group_message_sender_message_student_course_and_more.py
  chat/models.py
  study_group/migrations/0002_test_data.py
  tests/chat/test_chat.py
  tests/conftest.py
Labels: Status/In-Progress, enhancement, Ready for maintainer review

#38 Create an app for feed feature
  HighTeach/settings.py
  feed/__init__.py
  feed/admin.py
  feed/apps.py
  feed/migrations/0001_initial.py
  feed/migrations/__init__.py
  feed/models.py
  feed/tests.py
  feed/views.py
  tests/conftest.py
  tests/feed/test_feed.py
  tests/test_dummy.py
Labels: enhancement, Ready for maintainer review

#69 Renaming some models, fields and files
  chat/models.py
  course/admin.py
  course/migrations/0004_rename_teachercourses_teachercourse.py
  course/migrations/0005_rename_studentcourses_studentcourse.py
  course/migrations/0006_rename_course_id_review_course_and_more.py
  course/models.py
  tests/conftest.py
  tests/course/test_for_review_course.py
  tests/course/test_for_student_course.py
  tests/course/test_for_teacher_course.py
Labels: Status/New, bug, Ready for maintainer review

#72 Renaming some models, fields and files
  chat/models.py
  course/admin.py
  course/migrations/0004_rename_studentcourses_studentcourse_and_more.py
  course/models.py
  feed/models.py
  tests/conftest.py
  tests/course/test_for_review_course.py
  tests/course/test_for_student_course.py
  tests/course/test_for_teacher_course.py
  tests/feed/test_feed.py
Labels: duplicate, Ready for maintainer review

#68 Update the homepage and add tests
  HighTeach/middleware_login.py
  HighTeach/settings.py
  main/admin.py
  main/templates/base_home.html
  main/templates/main/homePage.html
  static/images/Lightbulb.png
  static/styles/homePage.css
  tests/conftest.py
  tests/main/test_home_page.py
Labels: Status/In-Progress, Ready for maintainer review

#75 New methods study group
  study_group/models.py
  tests/study_group/test_group_manager.py
  tests/study_group/test_study_group.py
Labels: enhancement, question, Ready for maintainer review, Ready for contributor review

#78 Add the option to logout and add a test
  HighTeach/middleware_login.py
  HighTeach/urls.py
  main/templates/base_home.html
  main/views.py
  tests/main/test_home_page.py
Labels: Status/New, Ready for maintainer review

#82 Add Base layout for logged in users
  main/templates/base_home.html
  main/templates/main/loggedInPage.html
  main/views.py
  static/images/blank_profile.png
  static/styles/loggedInPage.css
  tests/main/test_home_page.py
Labels: Status/New, Ready for maintainer review

#93 Moving the review fixtures to conftest file
  tests/conftest.py
  tests/course/test_for_review_course.py
Labels: Status/New, Ready for maintainer review

#97 Update side navbar in loggedInPage.html
  main/templates/main/loggedInPage.html
  static/styles/loggedInPage.css
Labels: Status/New, Ready for maintainer review

#86 Add Study group detail view
  HighTeach/urls.py
  main/templates/main/loggedInPage.html
  static/styles/study_group_stylesheet.css
  study_group/templates/leave_join_button.html
  study_group/templates/study_group_detail.html
  study_group/templates/study_group_update.html
  study_group/urls.py
  study_group/views.py
  tests/conftest.py
  tests/study_group/test_study_group.py
  tests/study_group/test_study_group_views.py
Labels: enhancement, Ready for maintainer review

#83 Create Course Table page
  HighTeach/urls.py
  course/models.py
  course/templates/course/courses.html
  course/urls.py
  course/views.py
  main/templates/main/loggedInPage.html
  static/styles/courses.table.css
  tests/course/test_course_pages.py
Labels: Status/New, enhancement, Ready for maintainer review

#89 Add review feature and tests
  HighTeach/urls.py
  course/forms.py
  course/templates/course/create_review.html
  course/templates/course/reviews_by_course.html
  course/urls.py
  course/views.py
  main/templates/base_home.html
  static/styles/style_review.css
  tests/course/test_review_view.py
Labels: Status/New, enhancement, Ready for maintainer review

#84 Create Add Course page
  course/forms.py
  course/templates/course/add_course.html
  course/templates/course/courses.html
  course/urls.py
  course/views.py
  static/styles/course.add.css
  tests/course/test_course_pages.py
Labels: enhancement, Ready for maintainer review

#80 Add study group list view
  HighTeach/settings.py
  main/templates/base_home.html
  study_group/forms.py
  study_group/templates/study_group_detail.html
  study_group/templates/study_group_hub.html
  study_group/templates/users_study_groups.html
  study_group/templatetags/__init__.py
  study_group/templatetags/study_group_tags.py
  study_group/urls.py
  study_group/views.py
  tests/conftest.py
  tests/study_group/test_study_group_views.py
Labels: enhancement, Ready for maintainer review

#85 Adding Course page
  course/models.py
  course/templates/course/course_page.html
  course/templates/course/courses.html
  course/urls.py
  course/views.py
  static/styles/course.page.css
  static/styles/js/mdb.min.js
  static/styles/mdb.min.css
  tests/course/test_course_pages.py
Labels: enhancement, Ready for maintainer review, Ready for contributor review

#74 Adding Tests and updete Users.models
  users/migrations/0003_alter_profile_bio_alter_profile_city_and_more.py
  users/migrations/0004_profile_image.py
  users/models.py
  users/signals.py
  users/tests.py
Labels: Status/New, enhancement, Ready for maintainer review, Ready for contributor review

#104 Added login page and tests for the login
  HighTeach/middleware_login.py
  HighTeach/settings.py
  HighTeach/urls.py
  main/templates/base_home.html
  main/templates/main/login.html
  main/views.py
  static/images/login_image.png
  static/styles/login.css
  tests/conftest.py
  tests/main/test_home_page.py
  tests/main/test_login_page.py
Labels: enhancement, Ready for maintainer review
