Repository redhat-beyond/HighTeach, pull requests merged in 2023-06, with the labels that each got.

#103 Add Chat UI functionality
  HighTeach/settings.py
  HighTeach/urls.py
  Pipfile
  Pipfile.lock
  chat/serializer.py
  chat/templates/chat/chat.html
  chat/urls.py
  chat/views.py
  course/models.py
  main/templates/base_home.html
  main/templates/main/loggedInPage.html
  static/styles/chat.css
  static/styles/js/chat.js
  study_group/models.py
  tests/chat/test_chat.py
  tests/conftest.py
  tests/course/test_for_student_course.py
Labels: Status/New, enhancement, Ready for maintainer review

#108 Add display user HTML document
  static/styles/user_list.css
  study_group/templates/study_group_detail.html
  users/templates/one_user.html
Labels: Status/New, enhancement, Ready for maintainer review

#99 Adding Feed to app
  HighTeach/urls.py
  feed/forms.py
  feed/models.py
  feed/templates/feed_page.html
  feed/urls.py
  feed/views.py
  static/styles/feed.css
  tests/feed/test_feed.py
Labels: Waiting for developer

#114 Improve UI in course pages
  course/models.py
  course/templates/course/add_course.html
  course/templates/course/course_page.html
  course/templates/course/courses.html
  course/templates/course/courses_table.html
  course/templates/course/courses_two_tables.html
  course/views.py
  media/images/test_image.jpg
  static/images/teacher.jpg
  static/styles/course.add.css
  static/styles/course.page.css
  static/styles/courses.table.css
  static/styles/mdb.min.css
  static/styles/student_course.css
  tests/conftest.py
  tests/course/test_course_pages.py
Labels: Status/New, enhancement, Ready for maintainer review

#119 Display profiles Images, fix tests and improve chat UI
  HighTeach/urls.py
  chat/serializer.py
  chat/templates/chat/chat.html
  chat/views.py
  main/templates/main/loggedInPage.html
  static/images/group_image.jpg
  static/styles/js/chat.js
  tests/chat/test_chat.py
  tests/conftest.py
Labels: Status/New, Ready for contributor review

#113 Add the option to see reviews in the course page
  course/forms.py
  course/models.py
  course/templates/course/course_page.html
  course/templates/course/create_review.html
  course/templates/course/reviews_by_course.html
  course/urls.py
  course/views.py
  tests/conftest.py
  tests/course/test_for_review_course.py
  tests/course/test_review_view.py
Labels: Status/New, enhancement, Ready for maintainer review

#115 Add requests to course page
  course/migrations/0005_alter_studentcourse_status.py
  course/models.py
  course/templates/course/course_page.html
  course/templates/student_course.html
  course/urls.py
  course/views.py
  media/images/test_image.jpg
  static/styles/student_course.css
  tests/conftest.py
  tests/course/test_course_pages.py
Labels: Status/New, enhancement, Ready for maintainer review

#121 Adding UI to the profile model
  HighTeach/urls.py
  main/templates/base_home.html
  main/templates/main/loggedInPage.html
  main/templates/one_course.html
  static/styles/edit_profile.css
  static/styles/one_course.css
  static/styles/profile_details.css
  tests/tests_user_views.py
  users/forms.py
  users/templates/users/edit-profile.html
  users/templates/users/index.html
  users/templates/users/profile_details.html
  users/templates/users/register.html
  users/urls.py
  users/views.py
Labels: Status/New, enhancement, Ready for contributor review
